apiVersion: apps/v1
kind: Deployment
metadata:
  name: batcher
  labels:
    app: batcher
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batcher
  template:
    metadata:
      labels:
        app: batcher
        azure.workload.identity/use: "true"
        azure.workload.identity/inject-proxy-sidecar: "true"
      annotations:
        # https://docs.dapr.io/reference/arguments-annotations-overview/
        dapr.io/enabled: "true"
        dapr.io/app-id: "batcher"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      serviceAccountName: batcher
      containers:
      - name: batcher
        image: $REGISTRY_NAME/batcher:latest
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always