apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: batcher-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0/5 * * * * *" # every 5 seconds
  - name: direction
    value: "input"
